CanteenVanLang/Models/ORDER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenVanLang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int ID { get; set; }
        public string ORDER_CODE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int STATUS { get; set; }
        public string FEEDBACK { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}

CanteenVanLang/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CanteenVanLang.Models;
using CanteenVanLang.Areas.Admin.Middleware;

namespace CanteenVanLang.Areas.Admin.Controllers
{
    [LoginVertification]
    public class OrderController : Controller
    {
        QUANLYCANTEENEntities model = new QUANLYCANTEENEntities();

        // GET: Admin/Order
        public ActionResult Index()
        {
            if((bool) Session["newOrder"])
            {
                var allOrder = model.ORDERs.OrderByDescending(ord => ord.ID).ToList();
                var newOrder = allOrder[allOrder.Count - 1];
                allOrder.Remove(newOrder);
                allOrder.OrderBy(ord => ord.DATE).ToList();
                allOrder.Add(newOrder);
                Session["newOrder"] = false;
                return View(allOrder);
            }
            else
            {
                var allOrders = model.ORDERs.OrderByDescending(ord => ord.DATE).ToList();
                return View(allOrders);
            }
        }

        public ActionResult Print(int id)
        {
            var printData = model.ORDERs.FirstOrDefault(ord => ord.ID == id);
            return View(printData);
        }

      

        private List<MENU> getMenuToday()
        {
            var today = DateTime.Now;
            var allMenu = model.MENUs.ToList();
            var menuToday = new List<MENU>();
            foreach (var item in allMenu)
            {
                if (item.DATE.Date == today.Date)
                    menuToday.Add(item);
            }
            return menuToday;
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<CUSTOMER> customers = model.CUSTOMERs.OrderByDescending(cust => cust.FULLNAME).ToList();
            List<MENU> menuToday = getMenuToday();
            ViewBag.customers = customers;
            ViewBag.menus = menuToday;
            ViewBag.IsNoMenu = false;
            if (menuToday.Count == 0)
            {
                ViewBag.IsNoMenu = true;
            }
            return View();
        }

        [HttpPost]
        public JsonResult Create(List<ORDER_DETAIL> orderDetails, string customerID)
        {
            if(customerID == null || customerID.Equals("none"))
            {
                return Json(new { success = false, caseFalse = "no customer" }, JsonRequestBehavior.AllowGet);
            }
            else if(orderDetails.Count == 0)
            {
                return Json(new { success = false, caseFalse = "no details" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var order = new ORDER();
                order.ACCOUNT_ID = (int)Session["userId"];
                order.CUSTOMER_ID = Int32.Parse(customerID);
                order.STATUS = 1;
                model.ORDERs.Add(order);
                model.SaveChanges();

                foreach (var detail in orderDetails)
                {
                    detail.ORDER_ID = order.ID;
                    model.ORDER_DETAIL.Add(detail);
                    model.SaveChanges();
                }
                Session["newOrder"] = true;
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var order = model.ORDERs.FirstOrDefault(ord => ord.ID == id);
            var listOrderDetails = model.ORDER_DETAIL.Where(detail => detail.ORDER_ID == id).ToList<ORDER_DETAIL>();
            var menus = getMenuOnDate((DateTime) order.DATE);
            ViewBag.listOrderDetails = listOrderDetails;
            ViewBag.menus = menus;
            if (menus.Count == 0)
            {
                ViewBag.IsNoMenu = true;
            }
            return View(order);
        }

        [HttpPost]
        public JsonResult Update(int id, List<ORDER_DETAIL> orderDetails, ORDER order)
        {
            if (orderDetails.Count == 0)
            {
                return Json(new { success = false, caseFalse = "no details" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var oldListOrderDetails = model.ORDER_DETAIL.Where(detail => detail.ORDER_ID == id).ToList();
                for(int i = 0; i < oldListOrderDetails.Count; i++)
                {
                    model.ORDER_DETAIL.Remove(oldListOrderDetails[i]);
                    model.SaveChanges();
                }

                foreach (var detail in orderDetails)
                {
                    detail.ORDER_ID = id;
                    model.ORDER_DETAIL.Add(detail);
                    model.SaveChanges();
                }

                var updatedOrder = model.ORDERs.FirstOrDefault(ord => ord.ID == id);
                updatedOrder.STATUS = order.STATUS;
                model.SaveChanges();

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var order = model.ORDERs.FirstOrDefault(ord => ord.ID == id);
            var listOrderDetails = model.ORDER_DETAIL.Where(detail => detail.ORDER_ID == id).ToList<ORDER_DETAIL>();
            ViewBag.listOrderDetails = listOrderDetails;
            return View(order);
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var order = model.ORDERs.FirstOrDefault(ord => ord.ID == id);
            if(order.STATUS == 2)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                order.STATUS = 4;
                model.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
        }

        private List<MENU> getMenuOnDate(DateTime date)
        {
            var allMenus = model.MENUs.ToList();
            var menus = new List<MENU>();
            foreach(var item in allMenus)
            {
                if (item.DATE.Date == date.Date)
                    menus.Add(item);
            }
            return menus;
        }

        [HttpPost]
        public JsonResult getPrice(string menuCode)
        {
            int price = model.MENUs.FirstOrDefault(menu => menu.MENU_CODE == menuCode).PRICE;
            return Json(new { success = true, value = price }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult checkQuantity(int quantity, int idMenu)
        {
            var menu = model.MENUs.FirstOrDefault(men => men.ID == idMenu);
            if(menu.QUANTITY >= quantity)
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }
    }
}

CanteenVanLang/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CanteenVanLang.Models;


namespace CanteenVanLang.Controllers
{
    [HandleError]
    public class FoodController : Controller
    {
        QUANLYCANTEENEntities model = new QUANLYCANTEENEntities();

        private List<FOOD> getFoods()
        {
            var listFoods = model.FOODs.OrderBy(f => f.FOOD_NAME).ToList();
            var listIdFood = getIdFoodInTodayMenu();
            for (int i = 0; i < listFoods.Count; i++)
            {
                if (listIdFood.Contains(listFoods[i].ID))
                    listFoods[i].STATUS = true;
                else
                    listFoods[i].STATUS = false;
            }
            return listFoods;
        }
        
        private List<int> getIdFoodInTodayMenu()
        {
            var menuToday = getMenuToday();
            var listIdFood = new List<int>();
            foreach(var item in menuToday)
            {
                listIdFood.Add(item.FOOD_ID);
            }
            return listIdFood;
        }

        private List<MENU> getMenuToday()
        {
            var today = DateTime.Now;
            var allMenu = model.MENUs.ToList();
            var menuToday = new List<MENU>();
            foreach(var item in allMenu)
            {
                if (item.DATE.Date == today.Date && item.STATUS == true)
                    menuToday.Add(item);
            }
            return menuToday;
        }

        public ActionResult Index()
        {
            var listFoods = getFoods();
            ViewBag.Categories = model.CATEGORies.Where(cate => cate.FOODs.Count > 0).ToList();
            return View(listFoods);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(400, "Bad Request");
            }
            var listFoods = getFoods();
            FOOD food = listFoods.FirstOrDefault(f => f.ID == id);
            if (food == null)
            {
                return HttpNotFound("Not Found");
            }
            ViewBag.NameFood = food.FOOD_NAME;
            ViewData["list"] = model.FOODs.Where(x => x.ID == id).ToList<FOOD>();
            return View(food);
        }

        public ActionResult Search(string searching)
        {
            var listFoods = getFoods();
            var searchResults = new List<FOOD>();
            foreach (var item in listFoods)
            {
                var name = ConvertToUnSign(item.FOOD_NAME).ToLower();
                var category = ConvertToUnSign(item.CATEGORY.CATEGORY_NAME).ToLower();
                var description = ConvertToUnSign(item.DESCRIPTION).ToLower();
                var searchingParsed = ConvertToUnSign(searching);
                if (name.Contains(searchingParsed) || category.Contains(searchingParsed) || item.PRICE.ToString().Contains(searching))
                {
                    searchResults.Add(item);
                }
            }
            ViewBag.Categories = model.CATEGORies.Where(cate => cate.FOODs.Count > 0).ToList();
            ViewBag.Searching = searching;
            ViewBag.Count = searchResults.Count;
            return View(searchResults);
        }

        private string ConvertToUnSign(string input)
        {
            input = input.Trim();
            for (int i = 0x20; i < 0x30; i++)
            {
                input = input.Replace(((char)i).ToString(), " ");
            }
            Regex regex = new Regex(@"\p{IsCombiningDiacriticalMarks}+");
            string str = input.Normalize(NormalizationForm.FormD);
            string str2 = regex.Replace(str, string.Empty).Replace('đ', 'd').Replace('Đ', 'D');
            while (str2.IndexOf("?") >= 0)
            {
                str2 = str2.Remove(str2.IndexOf("?"), 1);
            }
            return str2;
        }

        public ActionResult Category(int id)
        {
            var listFoods = getFoods().Where(food => food.CATEGORY_ID == id).ToList<FOOD>();
            ViewBag.Categories = model.CATEGORies.Where(cate => cate.FOODs.Count > 0).ToList();
            ViewBag.Category = model.CATEGORies.FirstOrDefault(cate => cate.ID == id);
            return View(listFoods);
        }
    }
}

CanteenVanLang/Views/Order/Cart.cshtml
@model IEnumerable<CanteenVanLang.Models.ORDER_DETAIL>
@using CanteenVanLang.Models
@{
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    var total = 0;
}

<section class="hero-wrap hero-wrap-2" style="background-image: url('@Url.Content("~/Images/Sliders/1.jpg")');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-0"><span class="mr-2"><a href="@Url.Action("Index", "Home")">Trang chủ <i class="fa fa-chevron-right"></i></a></span></p>
                <h2 class="mb-0 bread">Giỏ hàng</h2>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="table">
                <table class="table">
                    <thead class="thead-primary">
                        <tr>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                            <th>Tên món ăn</th>
                            <th>Giá</th>
                            <th style="width: 13%">Số lượng</th>
                            <th>Thành tiền</th>
                            <th>&nbsp;</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="alert" role="alert">
                                <td></td>
                                <td>
                                    <div class="img" style="background-image: url(@Url.Content("~"+item.MENU.FOOD.IMAGE_URL));"></div>
                                </td>
                                <td>
                                    <div class="email">
                                        <span>@item.MENU.FOOD.FOOD_NAME</span>
                                        @*<span>@item.MENU.FOOD.DESCRIPTION.Substring(0, 50)</span>*@
                                    </div>
                                </td>
                                <td>@item.UNIT_PRICE.ToString("N0")</td>
                                <td class="quantity">
                                    <div class="input-group">
                                        <input style="text-align: center" type="text" name="quantity" class="quantity form-control input-number" value="@item.QUANTITY" min="1" max="100">
                                    </div>
                                </td>
                                <td>@((item.UNIT_PRICE * item.QUANTITY).ToString("N0"))</td>
                                <td>
                                    <button onclick="remove(@item.ID, this)" type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true"><i class="fa fa-close"></i></span>
                                    </button>
                                </td>
                            </tr>
                            total += item.UNIT_PRICE * item.QUANTITY;
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col col-lg-3 col-md-4 mt-5 cart-wrap ftco-animate">
                <p class="">
                    <span style="font-weight: bold">Tổng tiền</span>
                    <span>&nbsp;</span>
                    <span id="total">@total.ToString("N0")</span>
                </p>
                <p class="text-center"><button type="button" id="check-out" class="btn btn-primary py-3 px-4">Đặt hàng</button></p>
            </div>
        </div>
    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function remove(idDetails, button) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("Remove", "Order")",
                data: JSON.stringify({ id: idDetails }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {
                    if (r.success) {
                        swal("Xóa món ăn khỏi giỏ hàng thành công", "", 'success');
                    } else {
                        swal("Lỗi", "Xóa món ăn khỏi giỏ hàng không thành công", 'error');
                    }
                }
            });
        }

    </script>

    <script>
        $("#check-out").click(function() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("check", "Order")",
                data: JSON.stringify({ a: "a" }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {
                    if (r.success) {
                        window.location.href = "@Url.Action("CheckOut", "Order")"
                    } else {
                        if (r.noItem) {
                            swal("Xin lỗi", "Vui lòng thêm món ăn vào đơn đặt hàng", 'error');
                        }
                        if (r.name) {
                            swal("Xin lỗi", "Số lượng còn của món ăn " + r.name + " không đủ, vui lòng điều chỉnh lại số lượng món", 'error');
                        }
                    }
                }
            });
        });
    </script>
}

CanteenVanLang/Views/Order/CheckOut.cshtml
@model IEnumerable<CanteenVanLang.Models.ORDER_DETAIL>
@{
    ViewBag.Title = "Xác nhận đặt hàng";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    var total = 0;
}


<section class="hero-wrap hero-wrap-2" style="background-image: url('@Url.Content("~/Images/Sliders/3.jpg")');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-0">
                    <span class="mr-2">
                        <a href="@Url.Action("Index", "Home")">
                            Trang chủ
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </span>
                    <span>
                        <a href="@Url.Action("Cart", "Order")">
                            Giỏ hàng
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </span>
                </p>
                <h2 style="margin-top: 10px" class="mb-0 bread">Đặt hàng</h2>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 ftco-animate">
                <form action="#" class="billing-form">
                    <h3 class="mb-4 billing-heading" style="text-align: center">Thông tin đơn hàng</h3>
                    <div class="row align-items-end">
                        <div class="col-md-8">
                            <div class="form-group" style="text-align: center">
                                <label for="firstname">Tên khách hàng</label>
                                <span>&nbsp;</span>
                                <span>&nbsp;</span>
                                <span>@Session["customerName"]</span>
                            </div>
                        </div>

                        <div class="w-100"></div>

                        <div class="w-100"></div>
                        <div class="col-md-8">
                            <div class="form-group" style="text-align: center">
                                <label for="streetaddress">Thời gian đặt</label>
                                <span>&nbsp;</span>
                                <span>&nbsp;</span>
                                <span>@DateTime.Now.Date.ToString("dd/MM/yyyy")</span>
                            </div>
                        </div>
                    </div>
                </form><!-- END -->
                <div class="table">
                    <table class="table">
                        <tr>

                            <th>Tên món ăn</th>
                            <th>Đơn giá</th>
                            <th style="width: 18%">Số lượng</th>
                            <th>Thành tiền</th>

                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="email">
                                        <span>@item.MENU.FOOD.FOOD_NAME</span>
                                    </div>
                                </td>
                                <td>@item.UNIT_PRICE.ToString("N0")</td>
                                <td>@item.QUANTITY</td>
                                <td>@((item.UNIT_PRICE * item.QUANTITY).ToString("N0"))</td>
                            </tr>
                            total += item.UNIT_PRICE * item.QUANTITY;
                        }
                    </table>
                </div>
                <div class="row justify-content-end">
                    <div class="col col-lg-3 col-md-4 mt-5 cart-wrap ftco-animate">
                        <p class="">
                            <span style="font-weight: bold">Tổng tiền</span>
                            <span>&nbsp;</span>
                            <span>@total.ToString("N0")</span>
                        </p>
                    </div>
                </div>
                <div class="row mt-5 pt-3" style="text-align: center">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <a href="@Url.Action("Cart", "Order")" class="btn btn-secondary py-2 px-4" style="width: 120px">Hủy</a>

                            <a href="@Url.Action("PlaceOrder", "Order")" class="btn btn-primary py-2 px-4" style="width: 120px; margin: 50px">Xác nhận</a>
                        </div>
                    </div>
                </div>
            </div> <!-- .col-md-8 -->
        </div>
    </div>
</section>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

CanteenVanLang/Views/Order/PlaceOrder.cshtml
@model CanteenVanLang.Models.ORDER
@using CanteenVanLang.Models
@{
    ViewBag.Title = "Đặt hàng thành công";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
    var listOrderDetails = ViewBag.listOrderDetails as List<ORDER_DETAIL>;
    var total = 0;
}

<section class="hero-wrap hero-wrap-2" style="background-image: url('@Url.Content("~/Images/Sliders/3.jpg")');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-0">
                    <span class="mr-2">
                        <a href="@Url.Action("Index", "Home")">
                            Trang chủ
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </span>
                    <span>
                        <a href="@Url.Action("Cart", "Order")">
                            Giỏ hàng
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </span>
                </p>
                <h2 class="mb-0 bread" style="margin-top: 10px">Đặt hàng thành công</h2>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 ftco-animate">
                <form action="#" class="billing-form">
                    <h3 class="mb-4 billing-heading" style="text-align: center">Thông tin đơn hàng</h3>
                    <div class="row align-items-end">
                        <div class="col-md-8">
                            <div class="form-group" style="text-align: center">
                                <label for="firstname">Tên khách hàng</label>
                                <span>&nbsp;</span>
                                <span>&nbsp;</span>
                                <span>@Model.CUSTOMER.FULLNAME</span>
                            </div>
                        </div>

                        <div class="w-100"></div>

                        <div class="w-100"></div>
                        <div class="col-md-8">
                            <div class="form-group" style="text-align: center">
                                <label for="streetaddress">Thời gian đặt</label>
                                <span>&nbsp;</span>
                                <span>&nbsp;</span>
                                <span>@(((DateTime)Model.DATE).ToString("dd/MM/yyyy"))</span>
                            </div>
                        </div>
                    </div>
                </form><!-- END -->
                <div class="table">
                    <table class="table">
                        <tr>

                            <th>Tên món ăn</th>
                            <th>Đơn giá</th>
                            <th style="width: 18%">Số lượng</th>
                            <th>Thành tiền</th>

                        </tr>
                        @foreach (var item in listOrderDetails)
                        {
                            <tr>
                                <td>
                                    <div class="email">
                                        <span>@item.MENU.FOOD.FOOD_NAME</span>
                                    </div>
                                </td>
                                <td>@item.UNIT_PRICE.ToString("N0")</td>
                                <td>@item.QUANTITY</td>
                                <td>@((item.UNIT_PRICE * item.QUANTITY).ToString("N0"))</td>
                            </tr>
                            total += item.UNIT_PRICE * item.QUANTITY;
                        }
                    </table>
                </div>
                <div class="row justify-content-end">
                    <div class="col col-lg-3 col-md-4 mt-5 cart-wrap ftco-animate">
                        <p class="">
                            <span style="font-weight: bold">Tổng tiền</span>
                            <span>&nbsp;</span>
                            <span>@total.ToString("N0")</span>
                        </p>
                    </div>
                </div>
                <div class="row mt-5 pt-3" style="text-align: center">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <a href="@Url.Action("Index", "Food")" class="btn btn-primary py-2 px-4" style="width: 120px; margin: 50px">Mua tiếp</a>
                        </div>
                    </div>
                </div>
            </div> <!-- .col-md-8 -->
        </div>
    </div>
</section>